### ISSUE TITLE
Jwplayer quality labels

### ISSUE THREAD

**Issue by Leonsss** [ArdiArtani/Photo-Google-Player-Script#1]
Hi!
One problem i noticed was the labels of the quality selector. Here is a screenshot
![capture](https://user-images.githubusercontent.com/28356411/27804616-26e2e3b2-6030-11e7-8877-dd6ff460a3c1.PNG)
And one thing else is that when the video is still encoding , for ex when the video is only in 360p quality it says : No playable source found. Don't know if this is an issue but i thought to let u know.

**Comment by nanoeray** [comment]
same issue. if video has only 360p player does not play video.

**Comment by ArdiArtani** [comment]
@Leonsss can you send me your video link.

**Comment by Leonsss** [comment]
@ArdiArtani http://dailyanime.byethost7.com/Photo-Google-Player-Script-master/

**Comment by ArdiArtani** [comment]
@Leonsss Fixed the problem download the new version.
