### ISSUE TITLE
Get iframe using get url parameter

### ISSUE THREAD

**Issue by michellewuu69** [ArdiArtani/Photo-Google-Player-Script#10]
Can I Get https://domains.com/index.php?url= [ URL Google Photos ]

If Can Please Teach Me :)

**Comment by viethqph00671** [comment]
just replace index.php line 3 to $url = $_GET['photoid'];
case closed

**Comment by michellewuu69** [comment]
how to connect this script to wordpress

**Comment by Zebraslive** [comment]
:1st_place_medal: 
https://jauntiest-ages.000webhostapp.com/drive/?url=https://photos.google.com/share/AF1QipOXUW1p13MNNHzL-7rk9czHQWPHFKH9Kthi8voN2KOqD-6Ft0xoDwJopwXj4xRX3w/photo/AF1QipODudUJ8VLqPa1tc7nUfJ6ClVzyAkg3tPrLEq4u?key=U3B2d0dtQlZPMGtrZnNfbVc5NVF3cFd2TGYzd2pR
:)
