### ISSUE TITLE
Share Limit

### ISSUE THREAD

**Issue by Myllz** [ArdiArtani/Photo-Google-Player-Script#11]
if movies get viewed too much you get an error. and you will see an error in google photos.

![image](https://user-images.githubusercontent.com/669814/31222090-2776f09a-a9c6-11e7-8d61-819d33439d70.png)

![image](https://user-images.githubusercontent.com/669814/31222165-79b06e86-a9c6-11e7-93fa-6b520d55e797.png)

You also can't download the file anymore...

**Comment by Zebraslive** [comment]
Just make a fallback script, I use backup servers for all videos. On error event replace video source or replace iframe url from within the iframe.

**Comment by dungvaph03374** [comment]
if google photo limit switch to google drive
