### ISSUE TITLE
Hi . Some videos have no audio and video can fix pls ?

### ISSUE THREAD

**Issue by matamune1994** [ArdiArtani/Photo-Google-Player-Script#12]
EX : No have audio https://drive.google.com/file/d/0BxvQyG88Ppcdbkd0alZENVNJNmc/view?usp=sharing

No have video : https://drive.google.com/file/d/0ByaRd0R0Qyatcmw2dVhQS0NDU0U/view 
can fix pls ?

**Comment by aalfiann** [comment]
Your link is playing fine, no problem and if it's happen, that problem is from Google Drive, so we can't fix it.
