### ISSUE TITLE
quality problem

### ISSUE THREAD

**Issue by nanoeray** [ArdiArtani/Photo-Google-Player-Script#2]
i'm using the latest version but now i have a problem. Players HD button shows reverse qualities. When u click HD button and activate it, player plays 360p, when u deactivate plays 720p. Here is an example,

[click to go](http://www.cartoontr.com/cartoonplayer/player.php?resim=sistem/resimler/resim.php?token=a2F0ZWdvcmlsZXIvZTFjOWIzNzFmYzhiYWYyYzc1OTFhMzE4MDlhZDNhMTI1NWUuanBn&access=aHR0cHM6Ly9waG90b3MuZ29vZ2xlLmNvbS91Lzcvc2hhcmUvQUYxUWlwUHV0TlB4UlQySzNrVnJyNFV3MEhpTmhXTVAtblhyQW14dDZXYVEyM1JqTV9BUlBfbEpnRWlKYVFzWjVSRHRHZy9waG90by9BRjFRaXBORFgweE85V182aXVmLVF0SUhiVUoxYnVnZXVqWERRYzZQRElicD9rZXk9T0c1b05IRXpWV2RITTBadVJGZFpkMjVqUTB4WVkwWm5NbEp2Wm5abg==&altyazi=)

**Comment by Leonsss** [comment]
@nanoeray I think u can fix your problem by switching the places of the qualities at gp.php
From `
if($count > 4) {
  | $v1080p = $decode.'=m37';
  | $v720p = $decode.'=m22';
  | $v360p = $decode.'=m18';
  | $linkDownload['1080p'] = $v1080p;
  | $linkDownload['720p'] = $v720p;
  | $linkDownload['360p'] = $v360p;
  | }
  | if($count > 3) {
  | $v720p = $decode.'=m22';
  | $v360p = $decode.'=m18';
  | $linkDownload['720p'] = $v720p;
  | $linkDownload['360p'] = $v360p;
  | }
  | if($count > 2) {
  | $v360p = $decode.'=m18';
  | $linkDownload['360p'] = $v360p;
  | }
 `
To: `if($count > 2) {
		$v360p = $decode.'=m18';
		$linkDownload['360p'] = $v360p;
	}
	
	if($count > 3) {
		$v720p = $decode.'=m22';
		$v360p = $decode.'=m18';
		$linkDownload['720p'] = $v720p;
		$linkDownload['360p'] = $v360p;
		
	}
	
	if($count > 4) {
		$v1080p = $decode.'=m37';
		$v720p = $decode.'=m22';
		$v360p = $decode.'=m18';
		$linkDownload['1080p'] = $v1080p;
		$linkDownload['720p'] = $v720p;
		$linkDownload['360p'] = $v360p;
	}	`

**Comment by nanoeray** [comment]
thanks, fixed.
