### ISSUE TITLE
Always serve from host server

### ISSUE THREAD

**Issue by vaguiners** [ArdiArtani/Photo-Google-Player-Script#24]
Can you help me to  make this to serve the file to user from server, avoiding user to have access to google photos servers?

**Comment by vaguiners** [comment]
Wich cache to avoid traffic limit from google photos

**Comment by Zebraslive** [comment]
@vaguiners use this gp.php. It caches links for 1 hour.
https://github.com/Zebraslive/Photo-Google-Player-Script/blob/Zebraslive-1080-patch/gp.php

**Comment by vaguiners** [comment]
@Zebraslive
But my server will serve the file to user from my server even if is not 100% cached or will serve by google site?

**Comment by vaguiners** [comment]
My goal is to serve all vids by my server, even the frist visitor, and let user be free from google. Can you help me?

**Comment by Zebraslive** [comment]
@vaguiners only way to do that is to save the video to your server with file_get_contents(). This would require a TON of bandwidth and server resources to host on your own server.

**Comment by vaguiners** [comment]
@Zebraslive the cache from this gp.php is not working for me
its always getting from google

**Comment by vaguiners** [comment]
@Zebraslive
its caching only file information. but it download the video again

**Comment by vaguiners** [comment]
this bypass the google limit?
