### ISSUE TITLE
dvd and low quality errors

### ISSUE THREAD

**Issue by d4lv** [ArdiArtani/Photo-Google-Player-Script#25]
videos with this quality is getting error "This video file cannot be played.
(Error Code: 224003)" dvd source 480pixel http://prntscr.com/ktccq9  and old videos http://prntscr.com/ktcdne , http://prntscr.com/ktceoy i can't find a fix to work for all i try to change this count but is working 2/3 or is working only the 1/3

	if($count > 7) {
		$linkDownload['1080p'] = $v1080p;
		$linkDownload['720p'] = $v720p;
		$linkDownload['360p'] = $v360p;
	} else if($count > 3) {
		$linkDownload['720p'] = $v720p;
		$linkDownload['360p'] = $v360p;
	} else if($count > 2) {
		$linkDownload['360p'] = $v360p;
	}

**Comment by vaguiners** [comment]
are you girl?

**Comment by d4lv** [comment]
@vaguiners wtf ??

**Comment by Abdamingani** [comment]
1.If you upload low quality video in google photos, 1080p and 720p is not working. it is better remove the some higher resulotion in this code and make the default resulotion (360p).

2.If you have a high resulotion videos in google photos? just wait a few month.
