### ISSUE TITLE
new update??

### ISSUE THREAD

**Issue by d4lv** [ArdiArtani/Photo-Google-Player-Script#32]
i dont know if anyone see it but is 2-3 days now 2/3 of my videos in gp is broken and i dont know if is from views or is randoms videos..

is any fix for what??

**Comment by Love656** [comment]
Hi you found solution? 
My videos also broken

**Comment by d4lv** [comment]
> Hi you found solution?
> My videos also broken

`<meta name="referrer" content="no-referrer" />` this is the fix
