### ISSUE TITLE
Undefined offset and undefined variable error!

### ISSUE THREAD

**Issue by alamgircsejnu** [ArdiArtani/Photo-Google-Player-Script#4]
Hi,
This script is what I am searching for 1 week. But it is showing error. I have attached a screenshot of the error.

![capture](https://user-images.githubusercontent.com/19221035/29100372-fc8ca31e-7ccc-11e7-95bf-83d0dfec2d2d.PNG)

Please help me.

**Comment by shaniax420** [comment]
#ArdiArtani same problem here pls fix this big thanks in advanced <3

**Comment by monster1777** [comment]
For first notice - wait for the video to process.
For the second - replace 
`return '['.rtrim($files, ',').']';`
with 
`if(@!$files)
        $files = '{"type": "video/mp4", "label": "HD", "file": "'.$decode .'=m18'.'"}';
    return '['.rtrim($files, ',').']';`
It worked for me, but yeah, doesn't work on localhost. When uploaded same code to my server, it works.

**Comment by alamgircsejnu** [comment]
I replaced the code and uploaded it to server. But now it's working some videos but not working for another some.

I am giving you link of a video for which it is not working.
https://photos.google.com/share/AF1QipOXUW1p13MNNHzL-7rk9czHQWPHFKH9Kthi8voN2KOqD-6Ft0xoDwJopwXj4xRX3w?key=U3B2d0dtQlZPMGtrZnNfbVc5NVF3cFd2TGYzd2pR

**Comment by ArdiArtani** [comment]
@alamgircsejnu The link works but you got the wrong sharing link https://photos.google.com/share/AF1QipOXUW1p13MNNHzL-7rk9czHQWPHFKH9Kthi8voN2KOqD-6Ft0xoDwJopwXj4xRX3w/photo/AF1QipODudUJ8VLqPa1tc7nUfJ6ClVzyAkg3tPrLEq4u?key=U3B2d0dtQlZPMGtrZnNfbVc5NVF3cFd2TGYzd2pR try this one.

**Comment by mirmarshall01** [comment]
@ArdiArtani can i use google drive link, is it possible ?

**Comment by viethqph00671** [comment]
@mirmarshall01 that's impossible mission bro, try to learn about video_get_info
