### ISSUE TITLE
1080p doesnt work

### ISSUE THREAD

**Issue by nanoeray** [ArdiArtani/Photo-Google-Player-Script#5]
here is a sample: http://www.cartoontr.com/cartoonplayer/player.php?resim=sistem/resimler/resim.php?token=a2F0ZWdvcmlsZXIvODRmODIwZWQ2YjQyZGNjNDRlOTVmOTY0NWJkZmRiYzE1OTkuanBn&access=aHR0cHM6Ly9waG90b3MuZ29vZ2xlLmNvbS9zaGFyZS9BRjFRaXBPVGMtS1FPM2hrWjlyT0dkM05EbWZfVmJYNS02WHI1dC1YUXh4ekdZVTBfano0SWxsWDdtbjZuQUllVkdodnB3L3Bob3RvL0FGMVFpcE1mdGwxeV9GNjB2bWVqaE1uUkNHQ1hCOWhZVTQ4UW1SY0ZCd1hpP2tleT1hRmxJWDE5b1NEVlBOVlJhY1ZWWVMwUm9YMDlxU1hOT2JuaG5aMWgz&altyazi=http://www.cartoontr.com/altyazi/GoT/s7/706.srt

when i choose 1080 player gets error 720 and 360 works fine

**Comment by threathgfx** [comment]
Same to me `http://japnime.com/_new/download.php?id=MzEwMzce`
I think they restricted it, the output of the video sends 500.

**Comment by monster1777** [comment]
It does work for me on one video, but on the other I see that 1080p disappeared, even in Google's player.

**Comment by ArdiArtani** [comment]
@monster1777 @nanoeray @monster1777 It works for me check out the demo. Can somebody share their google photos url.

**Comment by threathgfx** [comment]
@ArdiArtani  Yeep it works again
![screenshot_42](https://user-images.githubusercontent.com/29234610/29664455-398d1046-8902-11e7-925b-8dd87cf65c85.jpg)
