### ISSUE TITLE
Best way of getting shareable links?

### ISSUE THREAD

**Issue by chopraaa** [ArdiArtani/Photo-Google-Player-Script#9]
What's the best way of getting shareable links automatically if I have the photo/video ID like `AF1QipOA8ekaRD9KKkUs70aEJBu_JOnFwgMklDKg4jv4`?

**Comment by Zebraslive** [comment]
If you really want to do it without using the full url you can grab everything after  https://photos.google.com/share and use it as the id in url.  or make pretty urls combining all the id's in the url since there are 3 unique id's per photos link.

**Comment by chopraaa** [comment]
`https://photos.google.com/share` doesn't exist.

**Comment by ArdiArtani** [comment]
@chopraaa Download the new gp.php file and replace the code below on the index.php file

```
$url = 'https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB';
$getGP = getPhotoGoogle($url);
```
With
```
$id = $_GET['id'];
$gpURL = getURLbyID($id);
$getGP = getPhotoGoogle($gpURL);
```

http://yourdomain.com?id=AkgufhWkZkW6Rn8T6

**Comment by chopraaa** [comment]
This uses the short URL, not the ID.

For the ID of the photo/video, go to photos.google.com, right-click the video and get the URL,  `https://photos.google.com/photo/AF1QipMd5T07eUmgLwp1WRAHLyuN-kS1LqR0nKtwIItG`

this is the ID.

**Comment by Zebraslive** [comment]
https://jauntiest-ages.000webhostapp.com/drive/?url=AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB

https://jauntiest-ages.000webhostapp.com/drive/?url=https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB

these both work.

I'm doing something like this
```php
if (strpos($subfject, '/photo/') !== false && strpos($subfject, 'photos.google.com') === false) {
            $url = 'https://photos.google.com/share/'.$_GET['url'];
        } else { $url = $_GET['url'];  }
```
Feel free to use this api, it's public and unlimited.
Not sure if it's possible to get the full share link without sharing manually.

**Comment by chopraaa** [comment]
I don't want to use either of the URLs mate. Just the ID.

**Comment by chopraaa** [comment]
Why was this issue closed?

**Comment by nsultaan** [comment]
how to get http://demo.filedeo.stream/photos/?id=AkgufhWkZkW6Rn8T6 id 
if i share link https://photos.app.goo.gl/kdCgYWAPVZE0d9T43
after http://demo.filedeo.stream/photos/?id=kdCgYWAPVZE0d9T43 not work ??
sorry for bad english

**Comment by chopraaa** [comment]
@nsultaan Use the shortlink.

**Comment by nsultaan** [comment]
goo.gl short link??

**Comment by nsultaan** [comment]
how to get shortlink ? 
--help

**Comment by threathgfx** [comment]
@nsultaan edit this line
`$url="https://goo.gl/photos/$id";` to `$url="https://photos.app.goo.gl/$id";`
This will work.

**Comment by chopraaa** [comment]
Any help with using the ID would be great.

**Comment by threathgfx** [comment]
@chopraaa Well that's hard since we dont even know yet the permission within google photos and we all know that it needs something like the `key=` generated by there servers, if we know the algorithm of it then surely we can direct the id.

**Comment by aalfiann** [comment]
please dont do that, just fill the full url because the server will make more request and it will get slow in process.

**Comment by chopraaa** [comment]
@aalfiann Or put in a mechanism to cache the keys...

**Comment by d4lv** [comment]
why is not working the domain.com/gphotos/?url=normallinkfromgooglephotos??

**Comment by khalisafkari** [comment]
Not work Not work http://demo.filedeo.stream/photos/?id=https://photos.google.com/share/AF1QipMkdSWn7sOqwhmWANTAS6V_yVl5wWMVlS3cGILCrUNGiZKqBOxzewUDRjaziw1wiQ/photo/AF1QipP3y-6ywFafXVRGxpAxv_2q_UPnqz1s7n2R5SUN?key=cmM1T2VvM1dPOFdQYzVSRTN4UFBLYVZWdW0xOVJB

**Comment by d4lv** [comment]
guys what is the views limit now?? is 1k views-1video per day or is not anymore like this??

**Comment by chopraaa** [comment]
Irrespective of what the views limit is, create an issue on your own.
